title = "Nirvana - Brothel Pendle Hill"
baseURL = "https://onenirvana.com.au"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "./resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-RVKJRWZBWR"
enableRobotsTXT = true

# [languages]
#   [languages.en]
#     title = "Ananke"
#     weight = 1
#     contentDir = "content/en"
#     # languageDirection = 'rtl' for Right-To-Left languages
#   [languages.fr]
#     title = "Ananke Fr"
#     weight = 2
#     contentDir = "content/fr"

[sitemap]
  changefreq = ""
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "onenirvana.com.au"
  favicon = ""
  site_logo = ""
  description = "Nirvana - Brothel Pendle Hill"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"